### ISSUE TITLE
Stock at Trying to register to Pushe...

### ISSUE THREAD

**Issue by ghost1372** [pusheco/android-studio-sample#5]
سلام من از gradle استفاده میکنم
و طبق مستندات خود سایت پیشرفتم ولی برنامه فقط لاگ میده که
Trying to register to Pushe
و دستگاه رجیستر نمیشه
هم روی گوشی و هم شبیه ساز تست کردم
اندروید گوشی 7
گوگل پلی سرویس هم نصب هست

**Comment by mohammad1ta** [comment]
سلام @ghost1372 
منم چنین مشکلی دارم. ممکن هست بگین چطوری مشکلتون برطرف شد؟
با تشکر

**Comment by ghost1372** [comment]
@mohammad1ta  سلام مشکل برای 2 سال پیش بود
یادم نمیاد چطور حل شد 😅
اما با نسخه های اخر پوشه الان خیلی وقته که مشکلی ندارم دستورالعمل نصبش رو دقیق دنبال کنید

**Comment by mohammad1ta** [comment]
@ghost1372 
والا منم از آخرین نسخه استفاده میکنم،  دستور نصبشم که چیز خاصی نیست،  ۲۰ بار چکش کردم 😂😂.

**Comment by mahdi-malv** [comment]
@mohammad1ta 
سلام.

این مورد ممکنه بعضا پیش بیاد که سرور دیر جواب دیوایس رو بده و درخواست تکرار بشه.
اما درنهایت باید حل بشه و باید دیوایس هم ثبت بشه و هم اعلان دریافت کنه.
برنامه رو همه‌ی دیوایس‌ها و همیشه این مورد رو داره؟
و اصلا پوش نمی‌گیره؟

**Comment by mahdi-malv** [comment]
Feel free to reopen the issue if problem exists for you.

**Comment by javaherisaber** [comment]
@mahdi-malv I also have this issue 
here is my logcat dump :
```
I/Pushe: --------+ Started Initialization of Pushe 1.6.3 +--------
W/Pushe: Too many initialize calls made, skipping reinitialization
E/Pushe: Obtaining FCM token failed: java.io.IOException: SERVICE_NOT_AVAILABLE
E/Pushe: Obtaining FCM token failed: java.io.IOException: SERVICE_NOT_AVAILABLE
```
Is there any new restriction on Firebase services ?
or do i need to do new configuration on FCM?

`Library

**Comment by mahdi-malv** [comment]
**Error**: `E/Pushe: Obtaining FCM token failed: java.io.IOException: SERVICE_NOT_AVAILABLE`

Basically the **SERVICE_NOT_AVAILABLE** error happens when there is a problem when interacting with `Firebase`. Possible reasons and solutions are:

### **Internet is not avaiable**
 Check the connection

### Internet is connected but **Token is not set** in the `AndroidManifest.xml` file:
```xml
<meta-data android:name="co.ronash.pushe.token"
           android:value="PUSHE_{senderId}" />
```
inside `application` tag in the manifest.

### The Internet is connected, token is set, but the **FCM `API_KEY/SENDER_ID` is not valid:**
The `ApiKey` and `senderId` must belong to a valid existing firebase project. In this case make sure you use your own firebase credentials. Go to [Firebase console](https://console.firebase.google.com) and make a project and make a new app in Pushe console using your firebase apiKey/SenderId.

![image](https://user-images.githubusercontent.com/21319971/65384098-10669000-dd2b-11e9-87cd-2032513d8df2.png)
